### ISSUE TITLE
Generating variations in MidJourney only works one at a time

### ISSUE THREAD

**Issue by LouisDeconinck** [igolaizola/bulkai#1]
When I use the option to generate variations in MidJourney, the tool will only generate one variation or upscale one image at a time. It would be more efficient if the tool used 3 actions at the same time to upscale and generate variations at the same time from the same starting prompt.

I only tested this using 1 prompt, perhaps this issue is no longer present when providing multiple prompts as the tool might be working on all of those prompts at the same time.

**Comment by igolaizola** [comment]
Hello @LouisDeconinck!

You are correct that the tool is not optimized for a single prompt input, and will only run with a concurrency level of 1. However, if you provide 3 or more prompts, the tool will use the maximum concurrency for mid-journey.

While it would be possible to improve the tool to launch all jobs concurrently, I made the decision to avoid mixing results from different upscale/variation operations. In the end, matching the operation to the result is solely based on the prompt text, so keeping the same prompt operations in the same thread makes the process easier.
