### ISSUE TITLE
Sometimes the final result will still be webp and no response will be received

### ISSUE THREAD

**Issue by ZYKJShadow** [igolaizola/bulkai#12]
Below is the final result log

"content": "**\u003chttps://s.mj.run/LqZjmmrftcc\u003e A 180 pound kid is eating --q 2 --niji 5** - \u003c@926807951145074688\u003e (Open on website for full quality) (relaxed)",
  "components": [
    {
      "type": 1,
      "components": [
        {
          "type": 2,
          "style": 2,
          "label": "U1",
          "custom_id": "MJ::JOB::upsample::1::5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4"
        },
        {
          "type": 2,
          "style": 2,
          "label": "U2",
          "custom_id": "MJ::JOB::upsample::2::5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4"
        },
        {
          "type": 2,
          "style": 2,
          "label": "U3",
          "custom_id": "MJ::JOB::upsample::3::5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4"
        },
        {
          "type": 2,
          "style": 2,
          "label": "U4",
          "custom_id": "MJ::JOB::upsample::4::5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4"
        },
        {
          "type": 2,
          "style": 2,
          "emoji": {
            "name": "🔄"
          },
          "custom_id": "MJ::JOB::reroll::0::5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4::SOLO"
        }
      ]
    },
    {
      "type": 1,
      "components": [
        {
          "type": 2,
          "style": 2,
          "label": "V1",
          "custom_id": "MJ::JOB::variation::1::5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4"
        },
        {
          "type": 2,
          "style": 2,
          "label": "V2",
          "custom_id": "MJ::JOB::variation::2::5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4"
        },
        {
          "type": 2,
          "style": 2,
          "label": "V3",
          "custom_id": "MJ::JOB::variation::3::5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4"
        },
        {
          "type": 2,
          "style": 2,
          "label": "V4",
          "custom_id": "MJ::JOB::variation::4::5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4"
        }
      ]
    }
  ],
    "avatar": "4a79ea7cd151474ff9f6e08339d69380"
  },
  "attachments": [
    {
      "width": 2048,
      "url": "https://cdn.discordapp.com/attachments/981832774157762570/1095209919709466644/SAha_A_180_pound_kid_is_eating_5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4.webp",
      "size": 2069964,
      "proxy_url": "https://media.discordapp.net/attachments/981832774157762570/1095209919709466644/SAha_A_180_pound_kid_is_eating_5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4.webp",
      "id": "1095209919709466644",
      "height": 2048,
      "filename": "SAha_A_180_pound_kid_is_eating_5d78d1c5-ead9-4c39-a5d2-e0f9dbda9cc4.webp",
      "content_type": "image/webp"
    }
  ],
  "guild_id": "662267976984297473"
}

**Comment by igolaizola** [comment]
Thanks for reporting it.
It's fixed in the v1.0.9 I've just tagged.
