### ISSUE TITLE
couldn't find dm channel for bot

### ISSUE THREAD

**Issue by benjamen** [igolaizola/bulkai#15]
I get the following Issue and it does not run? Any ideas

C:\Users\XXX>bulkai generate --config bulkai.yaml
2023/04/12 15:33:49 loading session from session.yaml
2023/04/12 15:33:50 couldn't create bluewillow client: bluewillow: couldn't find dm channel for bot

**Comment by igolaizola** [comment]
Hi @benjamen!
You must manually join the discord server and open a DM chat with the bot before launching the tool.
