### ISSUE TITLE
Add midjourney error handlers

### ISSUE THREAD

**Issue by xiongqiangcs** [igolaizola/bulkai#29]
![image](https://user-images.githubusercontent.com/7856886/237050904-ee91a8b3-99ab-4860-a3fb-903275deacd8.png)
![image](https://github.com/igolaizola/bulkai/assets/7856886/62af4ef1-a673-4b36-b18c-4e49f985b66d)

**Comment by igolaizola** [comment]
Fixed here https://github.com/igolaizola/bulkai/pull/48
