### ISSUE TITLE
Can't setup the channel right

### ISSUE THREAD

**Issue by ewic1977** [igolaizola/bulkai#31]
Hi, thanks for your work. I'm trying to specify a channel as stated in the doc:
`channel` (string): Name of the channel to use in the form `guild/channel`

I can't get it to work. I've tried several things like putting a line like this in the yaml file where tipouletdoux#2321 and pixelart is my channel

channel: "tipouletdoux#2321/pixelart"
channel: "tipouletdoux/pixelart"
channel: tipouletdoux/pixelart

What am I doing wrong?
Thanks!

**Comment by igolaizola** [comment]
Hi! You need to use the guild ID and the channel ID. If you access to the channel through the discord website you can copy the numeric IDs from the URL.

**Comment by ewic1977** [comment]
Thank you so much using the IDs works great!
