### ISSUE TITLE
bulkai support midjourney v5.2

### ISSUE THREAD

**Issue by xiongqiangcs** [igolaizola/bulkai#39]

**Comment by igolaizola** [comment]
Could you elaborate this please? What exactly is not working from midjourney 5.2?

**Comment by xiongqiangcs** [comment]
> Could you elaborate this please? What exactly is not working from midjourney 5.2?

Sorry, I got it wrong, bulkai supports v5.2. In midjourney 5.2, Make Variations will change to vary(strong) and vary(subtle) after U1~U4 operations

**Comment by xiongqiangcs** [comment]
![image](https://github.com/igolaizola/bulkai/assets/7856886/efe15d98-a022-4f05-856d-eea9bf9141dd)

**Comment by igolaizola** [comment]
I have merged this https://github.com/igolaizola/bulkai/pull/43
But I haven't tested it because I don't currently have an active midjourney subscription

**Comment by xiongqiangcs** [comment]
> I have merged this #43 But I haven't tested it because I don't currently have an active midjourney subscription

I tried it, no problem
