### ISSUE TITLE
Difference in image quality between downloads and Discord

### ISSUE THREAD

**Issue by Auxority** [igolaizola/bulkai#40]
Hi there, thank you for making this tool!
It works great, however I just found a problem today.
Images that are Downloaded have less contrast and have slightly different colors than the original image in Discord.

![image](https://github.com/igolaizola/bulkai/assets/35202343/a4358783-9b0a-4a98-9c67-cec50d014fbb)

I hope you are able to solve this issue!

**Comment by igolaizola** [comment]
Hi @Auxority! Thank you for your report.

You're not upscaling the images, are you?
If that's the case, there might be an issue with how Bulkai crops the image.

Could you please confirm your settings so that I can investigate it further?

**Comment by Auxority** [comment]
Thank you for your quick response.

I just double checked, and I have Upscaling disabled.

**Comment by Auxority** [comment]
Just gotta add, when upscaling images, this issue does not occur.

**Comment by igolaizola** [comment]
@Auxority PR #53 should has fixed this problem.

**Comment by Auxority** [comment]
Very nice :)
Looking forward to the release.

**Comment by Auxority** [comment]
I saw you just created a release, thank you very much!

**Comment by igolaizola** [comment]
Happy to help 😄
