### ISSUE TITLE
retrying... discord: Invalid Form Body (50035)

### ISSUE THREAD

**Issue by nuwaofficialid** [igolaizola/bulkai#42]
first of all, this is nice helpful project, thanks for making this! 

![Screenshot 2023-07-04 130614](https://github.com/igolaizola/bulkai/assets/128625642/416fc39c-6731-4546-a9b0-0b62540ab4c9)
I just got this issue when i test generate.
I have logged in with my discord, and wrote the yaml file, also i have specified the channel name in the yaml file.

and, just asking, is it possible to logged in with bot token (maybe bot client +secret), instead of personal discord?

thanks in advance

**Comment by xiongqiangcs** [comment]
may be a problem with your channel settings in bulkai.yaml？
![image](https://github.com/igolaizola/bulkai/assets/7856886/cfa734a8-71da-4fb4-89b5-51ae6de65590)

**Comment by nuwaofficialid** [comment]
I just tried to change value from channel name (as it suggest in readme) to maybe channel id from the url.
so i change the channel value to this: "51297834712/12389281472" because my channel url is this:
https://discord.com/channels/**51297834712/12389281472**

it works now! thankss

**Comment by igolaizola** [comment]
Fantastic, you have successfully solved it! 👏
I have made improvements to the README to enhance its clarity.
