### ISSUE TITLE
Unrecognised parameter does not throw an error.

### ISSUE THREAD

**Issue by Auxority** [igolaizola/bulkai#47]
<img width="474" alt="image" src="https://github.com/igolaizola/bulkai/assets/35202343/ead7ad12-8bdb-4cf8-b823-0abd64f9fead">

When you use an invalid parameter like this, bulkai doesn't return anything. This does not seem like intended behaviour.

**Comment by igolaizola** [comment]
Fixed here https://github.com/igolaizola/bulkai/pull/48

**Comment by Auxority** [comment]
Great!
