### ISSUE TITLE
midjourney: couldn't find dm channel for bot

### ISSUE THREAD

**Issue by ZYKJShadow** [igolaizola/bulkai#5]
midjourney: couldn't find dm channel for bot

How do I fix it?

**Comment by gedw99** [comment]
me too.

maybe update Readme :)

**Comment by gedw99** [comment]
this ?  join https://discord.com/invite/midjourney

**Comment by gedw99** [comment]
think i found it but then got this:
"
You are not allowed to DM with slash commands
Free trial users are not allowed to DM the Midjourney Bot. You can upgrade to a paid plan to do so, by using the /subscribe command or visiting the website: https://midjourney.com/account
/imagine cats fightng
"

**Comment by aurevives** [comment]
> think i found it but then got this: " You are not allowed to DM with slash commands Free trial users are not allowed to DM the Midjourney Bot. You can upgrade to a paid plan to do so, by using the /subscribe command or visiting the website: https://midjourney.com/account /imagine cats fightng "

you need a paid subscription to use midjourney with bulkai

**Comment by igolaizola** [comment]
A few days ago, it was also possible for trial accounts to utilize the beginner channels (by using the `channel` parameter). However, trials have since been discontinued.

To pass the channel parameter, use the format: `guild-id/channel-id`, which is the same value displayed in the URL.

**Comment by gedw99** [comment]
Thanks !!

**Comment by satwiksunnam19** [comment]
if we subscribe to the midjourney do this work?
