### ISSUE TITLE
Url parameters in file names causing issues

### ISSUE THREAD

**Issue by Auxority** [igolaizola/bulkai#56]
Hey there, since a few days I'm having issues with url parameters in file names, which makes bulkai very unreliable at the moment.

Example output of `/tmp/output/1695739547.749379/images # ls`:

```
Hello_00000_00.png?ex=65144048&is=6512eec8&hm=11b95a7d5cd86f2c3758b6a59f22f3897f8e799983eaac8485b8e8c0d3bff5d8&
```

While giving this error:
```
❌ couldn't split `/tmp/output/1695739547.749379/images/Hello_00000_00.png?ex=65144048&is=6512eec8&hm=11b95a7d5cd86f2c3758b6a59f22f3897f8e799983eaac8485b8e8c0d3bff5d8&`: img: unsupported extension: .png?ex=65144048&is=6512eec8&hm=11b95a7d5cd86f2c3758b6a59f22f3897f8e799983eaac8485b8e8c0d3bff5d8&
```

**Comment by igolaizola** [comment]
Thanks for reporting @Auxority 
I've submitted a fix, could you check if it works?

**Comment by Auxority** [comment]
It works for me, thank you very much for fixing it so quickly!
