### ISSUE TITLE
PROBLEM: The file name, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by tarred5** [igolaizola/bulkai#57]
Hi, I'm getting the following message when I start the system with my prompts to generate the images: The file name, directory name, or volume label syntax is incorrect.

any idea what could be happening? My guess is that it could be a problem with the discord URL, as it continues to generate images on discord, but does not download them to my machine.

Please help me.

**Comment by Auxority** [comment]
Duplicate of https://github.com/igolaizola/bulkai/issues/56

**Comment by igolaizola** [comment]
Fixed here https://github.com/igolaizola/bulkai/pull/58
