### ISSUE TITLE
Some errors are not handled and cause the program to wait forever

### ISSUE THREAD

**Issue by ZYKJShadow** [igolaizola/bulkai#6]
1. Account usage limit

2. The v5 parameter cannot get the picture normally

3. Sometimes the arguments are wrong and discord gives an error, but the program keeps waiting

**Comment by igolaizola** [comment]
You're correct in stating that the tool doesn't receive error messages from midjourney. I have intentions to include support for this feature by analyzing the response messages. At the moment, I am not near my computer and therefore unable to develop this feature. However, I may address this issue after the Easter break.

In the meantime, could you please provide me with some examples of the different error messages you've received? 

V5 appears to be functioning correctly for me. Have you also experienced any error messages for V5 prompts?

By the way, the tool does not wait indefinitely, but it takes long. It does 5 attempts with a timeout of 10 minutes for each attempt.

**Comment by ZYKJShadow** [comment]
> You're correct in stating that the tool doesn't receive error messages from midjourney. I have intentions to include support for this feature by analyzing the response messages. At the moment, I am not near my computer and therefore unable to develop this feature. However, I may address this issue after the Easter break.
> 
> In the meantime, could you please provide me with some examples of the different error messages you've received?
> 
> V5 appears to be functioning correctly for me. Have you also experienced any error messages for V5 prompts?
> 
> By the way, the tool does not wait indefinitely, but it takes long. It does 5 attempts with a timeout of 10 minutes for each attempt.

For example, in prompt, discord will prompt that a sensitive word has been banned, but the program will wait (it does run out for 10 minutes, this is my mistake). V5 will not fail. However, the suffix written in the configuration file must be preceded by a space to be recognized

**Comment by ZYKJShadow** [comment]
> You're correct in stating that the tool doesn't receive error messages from midjourney. I have intentions to include support for this feature by analyzing the response messages. At the moment, I am not near my computer and therefore unable to develop this feature. However, I may address this issue after the Easter break.
> 
> In the meantime, could you please provide me with some examples of the different error messages you've received?
> 
> V5 appears to be functioning correctly for me. Have you also experienced any error messages for V5 prompts?
> 
> By the way, the tool does not wait indefinitely, but it takes long. It does 5 attempts with a timeout of 10 minutes for each attempt.

In addition, thank you very much for your reply

**Comment by igolaizola** [comment]
> For example, in prompt, discord will prompt that a sensitive word has been banned

Ok. So we have at least 2 error cases detected: banned words and invalid links. I will test it with those 👍
(I could even check the prompt for already known banned words and check if the links are valid before even sending the request to discord).

> However, the suffix written in the configuration file must be preceded by a space to be recognized

Yes, you're right. The prefix is directly added to the end of the prompt without no space, so if you want to add "--v 5" you have to set it like this `suffix: " --v 5"`. I'm not sure if I want to change the implementation of this, because someone may want set a suffix without space (for example: `suffix: ", style anime"`). However, I could add a note to the readme.

**Comment by ZYKJShadow** [comment]
> > For example, in prompt, discord will prompt that a sensitive word has been banned
> 
> Ok. So we have at least 2 error cases detected: banned words and invalid links. I will test it with those 👍 (I could even check the prompt for already known banned words and check if the links are valid before even sending the request to discord).
> 
> > However, the suffix written in the configuration file must be preceded by a space to be recognized
> 
> Yes, you're right. The prefix is directly added to the end of the prompt without no space, so if you want to add "--v 5" you have to set it like this `suffix: " --v 5"`. I'm not sure if I want to change the implementation of this, because someone may want set a suffix without space (for example: `suffix: ", style anime"`). However, I could add a note to the readme.

Yes, I would like to be able to determine if the content violates the community rules when I type it. Otherwise, some people often enter content that violates the community rules and will result in the account being suspended
