### ISSUE TITLE
No token generated after login discord

### ISSUE THREAD

**Issue by tkuanlun350** [igolaizola/bulkai#61]
Hi, I am using Windows_amd64 release. after .\bulkai.exe create-session and login in discord, there is no session file generated. 

The program just waiting. 

Thanks

full log:

2023/10/30 09:19:49 Starting browser
2023/10/30 09:19:51 ja3: 772,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,35-16-27-5-0-17513-13-23-11-45-51-10-65281-18-43,29-23-24,0
2023/10/30 09:19:53 user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
2023/10/30 09:19:53 language: en-US,en;q=0.9

**Comment by igolaizola** [comment]
I think this was fixed here https://github.com/igolaizola/bulkai/pull/69
Try it again with the latest version.
