### ISSUE TITLE
Could not obtain user agent

### ISSUE THREAD

**Issue by arthursouza** [igolaizola/bulkai#68]
Hi folks, I'm getting the following when creating session. Tried binary and tried building with go, same issue.

C:\Users\Arthur>bulkai create-session
2024/01/06 20:01:00 Starting browser
2024/01/06 20:01:02 ja3: 772,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,35-65037-18-16-45-51-43-0-27-13-5-10-11-23-17513-65281,29-23-24,0
2024/01/06 20:01:03 Browser stopped
2024/01/06 20:01:03 could not obtain user agent: invalid character 'p' after top-level value

**Comment by igolaizola** [comment]
Fixed in #69 
I've tagged a new version v1.1.8 to generate a new release.
