### ISSUE TITLE
The program is not effective

### ISSUE THREAD

**Issue by shiertier** [igolaizola/bulkai#7]
I installed bulkai according to the instructions, and after logging in, a session.yaml file containing the token was generated in the folder. Additionally, I configured the bulkai.yaml file with the following contents:

bot: midjourney
album: cute-animals
download: true
upscale: true
variation: false
thumbnail: true
suffix: " --ar 3:2"
prompt:"cute-animals"
proxy:127.0.0.1:7890

Afterwards, I ran the command 
`C:\Users\jie\go\bin>bulkai generate --config bulkai.yaml`

A window popped up asking "Do you want to allow this app to make changes to your device?", to which I clicked "Yes". 
However, nothing happened and a new line appeared in the cmd prompt:
`C:\Users\jie\go\bin>`

I also tried running 
`C:\Users\jie\go\bin>bulkai generate `
with the same result of a pop-up window and nothing happening. 
The program did not report any errors, but nothing seemed to have happened. 

I want to know if I made an error in my operation or if there is an issue with the program.

**Comment by igolaizola** [comment]
It seems that either the operating system or an antivirus program is preventing the application from running.

You might also consider attempting to run the application from a command prompt opened with administrative privileges.

**Comment by shiertier** [comment]
Solved the problem

**Comment by igolaizola** [comment]
Hi @shiertier! How did you fix the issue? It may help someone with the same problem.
