### ISSUE TITLE
Couldn't download error

### ISSUE THREAD

**Issue by TIEverton** [igolaizola/bulkai#77]
When trying to download the images, the following error is returning me, the prompts are being generated normally.

couldn't download `https://cdn.discordapp.com/attachments/link...`: discord: couldn't do request https://cdn.discordapp.com/attachments/link...: Get "https://cdn.discordapp.com/attachments/link....png": context canceled

**Comment by SomeBastardTookMyUserName** [comment]
I'm getting this error today.  Why is this issue closed down?  Or what were you and am I doing wrong to get this now?

**Comment by TIEverton** [comment]
In my case, after a few hours it returned to normal.

**Comment by SomeBastardTookMyUserName** [comment]
Had it last night and today, went away mysteriously this morning... So this must be something with Midjourney.

I did notice that the URL that failed when it was failing and the URL that would open up from the Discord interface were different.  If your fail URL was 

https://cdn.discordapp.com/attachments/link....png

Then the URL that MJ would generate when you "open in Browser" would be 

https://cdn.discordapp.com/attachments/link....png?ex=65d64af0&is....etc.

So there's extra code at the end.I have no idea what it is or what it means, but I thought I'd report it.

**Comment by igolaizola** [comment]
Some changes have been added to deal with this.

See: #79 #80 #82
