### ISSUE TITLE
If we use the url address of the image to generate, we also cannot receive the response.

### ISSUE THREAD

**Issue by ZYKJShadow** [igolaizola/bulkai#8]
I checked the reason, because the prompt given to the completion is not the same

I submitted this
![image](https://user-images.githubusercontent.com/45745703/230848699-adfea4e9-2e36-4742-beae-b693b823bb5f.png)

If I understand correctly, it should be used as the key of the map in the code, but it should be used for matching methods

But the response I received was this
![image](https://user-images.githubusercontent.com/45745703/230848910-819303c5-e01b-4f06-b33d-26a7a011e65f.png)

In addition to the image address change, there is also \u003 to deal with

**Comment by igolaizola** [comment]
That shouldn't be the issue. The bot is reading the updated response (it uses the nonce to make the match).
See:
https://github.com/igolaizola/bulkai/blob/eb80ac15c6ca6ef048446677cb9f066a4153d72f/pkg/ai/midjourney/midjourney.go#L368

Maybe the "niji" or "q" suffixes have something to do.
Could you try it again and give me the logs just after the interaction has been sent? The one saying "...waiting to start".

I'll try to take another look to it using your same example.

**Comment by ZYKJShadow** [comment]
> That shouldn't be the issue. The bot is reading the updated response (it uses the nonce to make the match). See:
> 
> https://github.com/igolaizola/bulkai/blob/eb80ac15c6ca6ef048446677cb9f066a4153d72f/pkg/ai/midjourney/midjourney.go#L368
> 
> Maybe the "niji" or "q" suffixes have something to do. Could you try it again and give me the logs just after the interaction has been sent? The one saying "...waiting to start".
> 
> I'll try to take another look to it using your same example.

this one

![image](https://user-images.githubusercontent.com/45745703/230856281-7f194823-8c25-446e-9504-57ebcf25e22d.png)

The address of the last image is different, so the prompt is different (key).

**Comment by ZYKJShadow** [comment]
There is also the question of whether the timeout can be reset if a progress change is received. Occasionally, the task will get close to completion but time out and fail

**Comment by igolaizola** [comment]
> > That shouldn't be the issue. The bot is reading the updated response (it uses the nonce to make the match). See:
> > https://github.com/igolaizola/bulkai/blob/eb80ac15c6ca6ef048446677cb9f066a4153d72f/pkg/ai/midjourney/midjourney.go#L368
> > 
> > Maybe the "niji" or "q" suffixes have something to do. Could you try it again and give me the logs just after the interaction has been sent? The one saying "...waiting to start".
> > I'll try to take another look to it using your same example.
> 
> this one
> 
> ![image](https://user-images.githubusercontent.com/45745703/230856281-7f194823-8c25-446e-9504-57ebcf25e22d.png)
> 
> The address of the last image is different, so the prompt is different (key).

Got it!

The first response doesn't have the converted link anymore (it used to have it).
Maybe the easiest fix is to just replace links. I'm already doing this for Bluewillow:

See https://github.com/igolaizola/bulkai/blob/eb80ac15c6ca6ef048446677cb9f066a4153d72f/pkg/ai/bluewillow/bluewillow.go#L497-L507

Until I fix this you won't be able to use links in your prompts.
