### ISSUE TITLE
using bulkai in ec2 server

### ISSUE THREAD

**Issue by umerjamal100** [igolaizola/bulkai#83]
Iam trying to use bulkai in an ec2 server so that i can connect with my FE on vercel, but when iam using `bulkai create-session` cmd it does not work because it does not support headless browser i guess also when i tried to use Xvfb it does not prompt to enter username and password, can we add this support so that we can use it in servers? and any other way to achieve this?

**Comment by igolaizola** [comment]
The `create-session` command launches a Chrome instance, so it's better if you run it on a desktop machine. You can then use the created session file on your server. The `generate` command doesn't use the Chrome browser, so you should be able to run it on your server without problems.
